#include "app/effects/effect_registry.h"

#include <QStringList>

namespace {
QVariantMap numberParameter(const QString &id, const QString &name,
                            double defaultValue, double minimum,
                            double maximum, double step,
                            const QString &unit = QString(), int decimals = 0) {
  return {{"id", id},           {"name", name},       {"type", "number"},
          {"default", defaultValue}, {"minimum", minimum}, {"maximum", maximum},
          {"step", step},       {"unit", unit},       {"decimals", decimals}};
}

QVariantMap effect(const QString &id, const QString &name,
                   const QString &category, const QString &description,
                   const QString &mediaType, const QVariantList &parameters,
                   const QString &icon = QStringLiteral("sliders-horizontal"),
                   bool previewSupported = false) {
  return {{"id", id},
          {"name", name},
          {"category", category},
          {"description", description},
          {"mediaType", mediaType},
          {"icon", icon},
          {"parameters", parameters},
          {"version", 1},
          {"previewSupported", previewSupported}};
}

QVariantMap maskParameter() {
  return {{"id", "mask"},
          {"name", "Mask"},
          {"type", "mask"},
          {"default", QVariantMap{{"x", 0.30},
                                  {"y", 0.35},
                                  {"width", 0.40},
                                  {"height", 0.30}}}};
}
} // namespace

QVariantList EffectRegistry::definitions() {
  static const QVariantList cached = []() {
    return QVariantList{
      effect("brightness_contrast", "Brightness & Contrast", "Video / Adjust",
             "Adjust brightness, contrast, and saturation.", "video",
             {numberParameter("brightness", "Brightness", 0, -100, 100, 1),
              numberParameter("contrast", "Contrast", 0, -100, 100, 1),
              numberParameter("saturation", "Saturation", 100, 0, 200, 1,
                              "%")},
             "sun", true),
      effect("monochrome", "Black & White", "Video / Adjust",
             "Remove all color from the clip.", "video", {}, "moon", true),
      effect("gaussian_blur", "Gaussian Blur", "Video / Blur & Sharpen",
             "Apply a smooth Gaussian blur.", "video",
             {numberParameter("amount", "Amount", 6, 0, 30, 0.1, {}, 1)},
             "sliders-horizontal", true),
      effect("box_blur", "Box Blur", "Video / Blur & Sharpen",
             "Apply a fast box blur.", "video",
             {numberParameter("radius", "Radius", 4, 0, 30, 1, "px")},
             "sliders-horizontal", true),
      effect("custom_blur", "Custom Blur", "Video / Blur & Sharpen",
             "Blur a pen-drawn region of a video or image clip.", "video",
             {numberParameter("amount", "Blurriness", 12, 0, 30, 0.1, {}, 1),
              maskParameter()},
             "pen-tool"),
      effect("sharpen", "Sharpen", "Video / Blur & Sharpen",
             "Increase local edge contrast.", "video",
             {numberParameter("amount", "Amount", 0.8, 0, 3, 0.1, {}, 1)}),
      effect("vignette", "Vignette", "Video / Stylize",
             "Darken the frame toward its edges.", "video",
             {numberParameter("strength", "Strength", 35, 0, 100, 1, "%")}),
      effect("invert", "Invert", "Video / Stylize",
             "Invert the image color channels.", "video", {}, "sun"),
      effect("film_grain", "Film Grain", "Video / Stylize",
             "Add animated monochromatic grain.", "video",
             {numberParameter("amount", "Amount", 18, 0, 100, 1, "%")}),
      effect("color_temperature", "Color Temperature", "Video / Adjust",
             "Warm or cool the image using a Kelvin temperature.", "video",
             {numberParameter("temperature", "Temperature", 6500, 1000,
                              40000, 100, "K"),
              numberParameter("mix", "Mix", 100, 0, 100, 1, "%")},
             "sun"),
      effect("pixelate", "Mosaic", "Video / Stylize",
             "Replace image detail with adjustable pixel blocks.", "video",
             {numberParameter("blockSize", "Block Size", 16, 2, 128, 1,
                              "px")},
             "image"),
      effect("edge_detect", "Find Edges", "Video / Stylize",
             "Detect and blend image edges with the source color.", "video",
             {numberParameter("threshold", "Threshold", 20, 1, 80, 1,
                              "%")},
             "image"),
      effect("sepia", "Sepia", "Video / Stylize",
             "Apply a warm sepia channel mix.", "video", {}, "sun"),
      effect("lens_correction", "Lens Correction", "Video / Distort",
             "Correct barrel or pincushion lens distortion.", "video",
             {numberParameter("k1", "Curvature", 0, -100, 100, 1, "%"),
              numberParameter("k2", "Fine Curvature", 0, -100, 100, 1,
                              "%")},
             "sliders-horizontal"),
      effect("deinterlace", "Deinterlace", "Video / Video",
             "Convert interlaced frames to progressive frames.", "video", {},
             "film"),
      effect("audio_denoise", "Denoise", "Audio / Noise Reduction",
             "Reduce steady broadband background noise.", "audio",
             {numberParameter("strength", "Strength", 35, 0, 100, 1, "%")},
             "volume-2"),
      effect("high_pass", "High-Pass Filter", "Audio / Filter and EQ",
             "Remove frequencies below the cutoff.", "audio",
             {numberParameter("frequency", "Frequency", 80, 20, 1000, 1,
                              "Hz")},
             "sliders-horizontal"),
      effect("low_pass", "Low-Pass Filter", "Audio / Filter and EQ",
             "Remove frequencies above the cutoff.", "audio",
             {numberParameter("frequency", "Frequency", 16000, 1000, 22000,
                              10, "Hz")},
             "sliders-horizontal"),
      effect("compressor", "Compressor", "Audio / Amplitude",
             "Control peaks and reduce dynamic range.", "audio",
             {numberParameter("threshold", "Threshold", -18, -40, -6, 1,
                              "dB"),
              numberParameter("ratio", "Ratio", 3, 1, 10, 0.1, ":1", 1),
              numberParameter("makeup", "Makeup", 2, 0, 12, 0.5, "dB", 1)},
             "volume-2"),
      effect("limiter", "Hard Limiter", "Audio / Amplitude",
             "Prevent output peaks from exceeding a ceiling.", "audio",
             {numberParameter("ceiling", "Ceiling", -1, -12, 0, 0.1, "dB",
                              1)},
             "volume-2"),
      effect("echo", "Echo", "Audio / Delay and Reverb",
             "Add a delayed, decaying copy of the signal.", "audio",
             {numberParameter("delay", "Delay", 180, 10, 1000, 1, "ms"),
              numberParameter("decay", "Decay", 0.35, 0.1, 0.9, 0.05, {},
                              2)},
             "volume-2"),
      effect("vocal_reducer", "Center Vocal Reduction",
             "Audio / Special", "Reduce centered content in a stereo mix.",
             "audio", {}, "volume-x"),
      effect("bass", "Bass", "Audio / Filter and EQ",
             "Boost or cut low frequencies.", "audio",
             {numberParameter("gain", "Gain", 3, -24, 24, 0.5, "dB", 1),
              numberParameter("frequency", "Frequency", 100, 40, 500, 1,
                              "Hz")},
             "volume-2"),
      effect("treble", "Treble", "Audio / Filter and EQ",
             "Boost or cut high frequencies.", "audio",
             {numberParameter("gain", "Gain", 3, -24, 24, 0.5, "dB", 1),
              numberParameter("frequency", "Frequency", 3000, 1000, 16000,
                              10, "Hz")},
             "volume-2"),
      effect("deesser", "De-Esser", "Audio / Noise Reduction",
             "Reduce harsh sibilance in dialogue and vocals.", "audio",
             {numberParameter("intensity", "Intensity", 45, 0, 100, 1,
                              "%"),
              numberParameter("maximum", "Maximum Reduction", 60, 0, 100,
                              1, "%"),
              numberParameter("focus", "Frequency Focus", 50, 0, 100, 1,
                              "%")},
             "volume-2"),
      effect("noise_gate", "Noise Gate", "Audio / Amplitude",
             "Attenuate audio that falls below a threshold.", "audio",
             {numberParameter("threshold", "Threshold", -36, -36, -6, 1,
                              "dB"),
              numberParameter("ratio", "Ratio", 4, 1, 20, 0.5, ":1", 1),
              numberParameter("attack", "Attack", 15, 1, 250, 1, "ms"),
              numberParameter("release", "Release", 180, 10, 1000, 1,
                              "ms")},
             "volume-2"),
      effect("loudness_normalize", "Loudness Normalize",
             "Audio / Amplitude", "Normalize output to an EBU R128 target.",
             "audio",
             {numberParameter("target", "Target Loudness", -16, -30, -5,
                              0.5, " LUFS", 1),
              numberParameter("truePeak", "True Peak", -1.5, -9, 0, 0.1,
                              " dBTP", 1)},
             "volume-2"),
      effect("chorus", "Chorus", "Audio / Modulation",
             "Add a gently modulated delayed voice.", "audio",
             {numberParameter("speed", "Speed", 0.8, 0.1, 5, 0.1, " Hz",
                              1),
              numberParameter("depth", "Depth", 2, 0.1, 10, 0.1, " ms",
                              1)},
             "volume-2"),
      effect("flanger", "Flanger", "Audio / Modulation",
             "Apply a sweeping short-delay modulation effect.", "audio",
             {numberParameter("speed", "Speed", 0.5, 0.1, 10, 0.1, " Hz",
                              1),
              numberParameter("depth", "Depth", 2, 0, 10, 0.1, " ms", 1),
              numberParameter("feedback", "Feedback", 0, -90, 90, 1, "%"),
              numberParameter("mix", "Mix", 70, 0, 100, 1, "%")},
             "volume-2"),
      effect("stereo_widener", "Stereo Widener", "Audio / Stereo Imagery",
             "Increase the perceived width of stereo audio.", "audio",
             {numberParameter("delay", "Delay", 20, 1, 100, 1, " ms"),
              numberParameter("feedback", "Feedback", 30, 0, 90, 1, "%"),
              numberParameter("crossfeed", "Crossfeed", 30, 0, 80, 1, "%"),
              numberParameter("dryMix", "Dry Mix", 80, 0, 100, 1, "%")},
             "volume-2")};
  }();
  return cached;
}

QVariantMap EffectRegistry::definition(const QString &effectId) {
  for (const auto &value : definitions()) {
    const QVariantMap item = value.toMap();
    if (item.value("id").toString() == effectId)
      return item;
  }
  return {};
}

bool EffectRegistry::supportsClip(const QVariantMap &definition,
                                  const QString &clipKind, bool hasAudio) {
  const QString mediaType = definition.value("mediaType").toString();
  if (mediaType == QStringLiteral("audio"))
    return hasAudio && clipKind != QStringLiteral("subtitle");
  return clipKind == QStringLiteral("video") ||
         clipKind == QStringLiteral("image");
}
