#include "app/effects/effect_registry.h"

#include <QStringList>

namespace {
QVariantMap numberParameter(const QString &id, const QString &name,
                            double defaultValue, double minimum,
                            double maximum, double step,
                            const QString &unit = QString(), int decimals = 0) {
  return {{"id", id},           {"name", name},       {"type", "number"},
          {"default", defaultValue}, {"minimum", minimum}, {"maximum", maximum},
          {"step", step},       {"unit", unit},       {"decimals", decimals}};
}

QVariantMap effect(const QString &id, const QString &name,
                   const QString &category, const QString &description,
                   const QString &mediaType, const QVariantList &parameters,
                   const QString &icon = QStringLiteral("sliders-horizontal"),
                   bool previewSupported = false) {
  return {{"id", id},
          {"name", name},
          {"category", category},
          {"description", description},
          {"mediaType", mediaType},
          {"icon", icon},
          {"parameters", parameters},
          {"version", 1},
          {"previewSupported", previewSupported}};
}

QVariantMap boolParameter(const QString &id, const QString &name,
                          bool defaultValue = false) {
  return {{"id", id},
          {"name", name},
          {"type", "bool"},
          {"default", defaultValue}};
}

QVariantMap maskParameter() {
  return {{"id", "mask"},
          {"name", "Mask"},
          {"type", "mask"},
          {"default", QVariantMap{{"x", 0.30},
                                  {"y", 0.35},
                                  {"width", 0.40},
                                  {"height", 0.30}}}};
}
} // namespace

QVariantList EffectRegistry::definitions() {
  static const QVariantList cached = []() {
    return QVariantList{
      effect("brightness_contrast", "Brightness & Contrast", "Video / Adjust",
             "Adjust brightness, contrast, and saturation.", "video",
             {numberParameter("brightness", "Brightness", 0, -100, 100, 1),
              numberParameter("contrast", "Contrast", 0, -100, 100, 1),
              numberParameter("saturation", "Saturation", 100, 0, 200, 1,
                              "%")},
             "sun", true),
      effect("monochrome", "Black & White", "Video / Adjust",
             "Remove all color from the clip.", "video", {}, "moon", true),
      effect("gaussian_blur", "Gaussian Blur", "Video / Blur & Sharpen",
             "Apply a smooth Gaussian blur.", "video",
             {numberParameter("amount", "Amount", 6, 0, 30, 0.1, {}, 1)},
             "sliders-horizontal", true),
      effect("box_blur", "Box Blur", "Video / Blur & Sharpen",
             "Apply a fast box blur.", "video",
             {numberParameter("radius", "Radius", 4, 0, 30, 1, "px")},
             "sliders-horizontal", true),
      effect("custom_blur", "Custom Blur", "Video / Blur & Sharpen",
             "Blur a pen-drawn region of a video or image clip.", "video",
             {numberParameter("amount", "Blurriness", 12, 0, 30, 0.1, {}, 1),
              maskParameter()},
             "pen-tool"),
      effect("sharpen", "Sharpen", "Video / Blur & Sharpen",
             "Increase local edge contrast.", "video",
             {numberParameter("amount", "Amount", 0.8, 0, 3, 0.1, {}, 1)}),
      effect("vignette", "Vignette", "Video / Stylize",
             "Darken the frame toward its edges.", "video",
             {numberParameter("strength", "Strength", 35, 0, 100, 1, "%")}),
      effect("invert", "Invert", "Video / Stylize",
             "Invert the image color channels.", "video", {}, "sun"),
      effect("film_grain", "Film Grain", "Video / Stylize",
             "Add animated monochromatic grain.", "video",
             {numberParameter("amount", "Amount", 18, 0, 100, 1, "%")}),
      effect("color_temperature", "Color Temperature", "Video / Adjust",
             "Warm or cool the image using a Kelvin temperature.", "video",
             {numberParameter("temperature", "Temperature", 6500, 1000,
                              40000, 100, "K"),
              numberParameter("mix", "Mix", 100, 0, 100, 1, "%")},
             "sun"),
      effect("pixelate", "Mosaic", "Video / Stylize",
             "Replace image detail with adjustable pixel blocks.", "video",
             {numberParameter("blockSize", "Block Size", 16, 2, 128, 1,
                              "px")},
             "image"),
      effect("edge_detect", "Find Edges", "Video / Stylize",
             "Detect and blend image edges with the source color.", "video",
             {numberParameter("threshold", "Threshold", 20, 1, 80, 1,
                              "%")},
             "image"),
      effect("sepia", "Sepia", "Video / Stylize",
             "Apply a warm sepia channel mix.", "video", {}, "sun"),
      effect("lens_correction", "Lens Correction", "Video / Distort",
             "Correct barrel or pincushion lens distortion.", "video",
             {numberParameter("k1", "Curvature", 0, -100, 100, 1, "%"),
              numberParameter("k2", "Fine Curvature", 0, -100, 100, 1,
                              "%")},
             "sliders-horizontal"),
      effect("deinterlace", "Deinterlace", "Video / Video",
             "Convert interlaced frames to progressive frames.", "video", {},
             "film"),
      effect("hue_saturation", "Hue & Saturation", "Video / Adjust",
             "Rotate hue and scale saturation.", "video",
             {numberParameter("hue", "Hue", 0, -180, 180, 1, "°"),
              numberParameter("saturation", "Saturation", 100, 0, 300, 1, "%"),
              numberParameter("brightness", "Brightness", 0, -3, 3, 0.1, {},
                              1)},
             "sun", true),
      effect("exposure", "Exposure", "Video / Adjust",
             "Correct exposure in stops and lift or crush the black level.",
             "video",
             {numberParameter("exposure", "Exposure", 0, -3, 3, 0.05, " EV",
                              2),
              numberParameter("black", "Black Level", 0, -0.5, 0.5, 0.01, {},
                              2)},
             "sun", true),
      effect("levels", "Levels", "Video / Adjust",
             "Remap the input and output black and white points.", "video",
             {numberParameter("inputBlack", "Input Black", 0, 0, 90, 1, "%"),
              numberParameter("inputWhite", "Input White", 100, 10, 100, 1,
                              "%"),
              numberParameter("outputBlack", "Output Black", 0, 0, 90, 1, "%"),
              numberParameter("outputWhite", "Output White", 100, 10, 100, 1,
                              "%")},
             "sliders-horizontal"),
      effect("gamma", "Gamma", "Video / Adjust",
             "Brighten or darken midtones without moving black or white.",
             "video",
             {numberParameter("gamma", "Gamma", 1, 0.1, 4, 0.01, {}, 2),
              numberParameter("weight", "Highlight Rolloff", 1, 0, 1, 0.01,
                              {}, 2)},
             "sun"),
      effect("color_balance", "Color Balance", "Video / Adjust",
             "Shift color separately in shadows, midtones and highlights.",
             "video",
             {numberParameter("shadowsRed", "Shadows Red", 0, -100, 100, 1,
                              "%"),
              numberParameter("shadowsGreen", "Shadows Green", 0, -100, 100, 1,
                              "%"),
              numberParameter("shadowsBlue", "Shadows Blue", 0, -100, 100, 1,
                              "%"),
              numberParameter("midtonesRed", "Midtones Red", 0, -100, 100, 1,
                              "%"),
              numberParameter("midtonesGreen", "Midtones Green", 0, -100, 100,
                              1, "%"),
              numberParameter("midtonesBlue", "Midtones Blue", 0, -100, 100, 1,
                              "%"),
              numberParameter("highlightsRed", "Highlights Red", 0, -100, 100,
                              1, "%"),
              numberParameter("highlightsGreen", "Highlights Green", 0, -100,
                              100, 1, "%"),
              numberParameter("highlightsBlue", "Highlights Blue", 0, -100,
                              100, 1, "%"),
              boolParameter("preserveLightness", "Preserve Lightness", true)},
             "sliders-horizontal"),
      effect("vibrance", "Vibrance", "Video / Adjust",
             "Raise saturation of muted colors and leave skin tones alone.",
             "video",
             {numberParameter("intensity", "Intensity", 0, -100, 100, 1, "%")},
             "sun", true),
      effect("tint", "Tint", "Video / Adjust",
             "Push the whole image toward a single hue.", "video",
             {numberParameter("hue", "Hue", 30, 0, 360, 1, "°"),
              numberParameter("saturation", "Saturation", 40, 0, 100, 1, "%"),
              numberParameter("mix", "Preserve Luma", 80, 0, 100, 1, "%")},
             "sun"),
      effect("directional_blur", "Directional Blur", "Video / Blur & Sharpen",
             "Smear the image along a single angle.", "video",
             {numberParameter("angle", "Angle", 45, 0, 360, 1, "°"),
              numberParameter("radius", "Length", 8, 0, 40, 0.5, {}, 1)},
             "sliders-horizontal"),
      effect("motion_blur", "Motion Blur", "Video / Blur & Sharpen",
             "Average neighbouring frames so motion trails.", "video",
             {numberParameter("frames", "Frames", 4, 2, 16, 1)}, "film"),
      effect("smart_blur", "Smart Blur", "Video / Blur & Sharpen",
             "Blur flat areas while keeping edges sharp.", "video",
             {numberParameter("radius", "Radius", 2, 0.1, 5, 0.1, {}, 1),
              numberParameter("strength", "Strength", 0.8, -1, 1, 0.05, {}, 2),
              numberParameter("threshold", "Edge Threshold", 0, -30, 30, 1)},
             "sliders-horizontal"),
      effect("unsharp_mask", "Unsharp Mask", "Video / Blur & Sharpen",
             "Sharpen with a controllable radius and color amount.", "video",
             {numberParameter("radius", "Radius", 2, 1, 11, 1, "px"),
              numberParameter("amount", "Amount", 1.2, -2, 5, 0.1, {}, 2),
              numberParameter("colorAmount", "Color Amount", 0, -2, 5, 0.1, {},
                              2)},
             "sliders-horizontal"),
      effect("video_denoise", "Denoise", "Video / Noise & Grain",
             "Reduce sensor noise spatially and across frames.", "video",
             {numberParameter("luma", "Luma", 4, 0, 30, 0.5, {}, 1),
              numberParameter("chroma", "Chroma", 3, 0, 30, 0.5, {}, 1),
              numberParameter("temporal", "Temporal", 6, 0, 30, 0.5, {}, 1)},
             "sliders-horizontal"),
      effect("deband", "Deband", "Video / Noise & Grain",
             "Break up banding in gradients and flat skies.", "video",
             {numberParameter("threshold", "Threshold", 4, 0.1, 50, 0.1, "%",
                              1),
              numberParameter("range", "Range", 16, 1, 64, 1, "px")},
             "sliders-horizontal"),
      effect("deflicker", "Deflicker", "Video / Noise & Grain",
             "Even out brightness pulsing between frames.", "video",
             {numberParameter("size", "Frames", 5, 2, 129, 1)}, "film"),
      effect("posterize", "Posterize", "Video / Stylize",
             "Quantize every channel to a fixed number of levels.", "video",
             {numberParameter("levels", "Levels", 8, 2, 32, 1)}, "image"),
      effect("emboss", "Emboss", "Video / Stylize",
             "Raise edges into relief while keeping the original color.",
             "video",
             {numberParameter("strength", "Strength", 1, 0.2, 3, 0.1, {}, 1)},
             "image"),
      effect("chromatic_aberration", "Chromatic Aberration", "Video / Stylize",
             "Offset the red and blue channels for a lens fringe look.",
             "video",
             {numberParameter("horizontal", "Horizontal", 4, -30, 30, 1, "px"),
              numberParameter("vertical", "Vertical", 0, -30, 30, 1, "px")},
             "image"),
      effect("chroma_key", "Chroma Key", "Video / Keying",
             "Knock out a colored background so lower tracks show through.",
             "video",
             {numberParameter("keyHue", "Key Hue", 120, 0, 360, 1, "°"),
              numberParameter("similarity", "Similarity", 15, 1, 60, 1, "%"),
              numberParameter("blend", "Edge Blend", 10, 0, 60, 1, "%"),
              boolParameter("suppressSpill", "Suppress Spill", true)},
             "pen-tool"),
      effect("luma_key", "Luma Key", "Video / Keying",
             "Knock out pixels by brightness instead of by color.", "video",
             {numberParameter("threshold", "Threshold", 10, 0, 100, 1, "%"),
              numberParameter("tolerance", "Tolerance", 20, 0, 100, 1, "%"),
              numberParameter("softness", "Softness", 10, 0, 100, 1, "%")},
             "pen-tool"),
      effect("despill", "Spill Suppression", "Video / Keying",
             "Remove screen color bleeding onto the subject's edges.", "video",
             {numberParameter("mix", "Amount", 50, 0, 100, 1, "%"),
              numberParameter("expand", "Expand", 10, 0, 100, 1, "%"),
              boolParameter("blueScreen", "Blue Screen", false)},
             "pen-tool"),
      effect("audio_denoise", "Denoise", "Audio / Noise Reduction",
             "Reduce steady broadband background noise.", "audio",
             {numberParameter("strength", "Strength", 35, 0, 100, 1, "%")},
             "volume-2"),
      effect("high_pass", "High-Pass Filter", "Audio / Filter and EQ",
             "Remove frequencies below the cutoff.", "audio",
             {numberParameter("frequency", "Frequency", 80, 20, 1000, 1,
                              "Hz")},
             "sliders-horizontal"),
      effect("low_pass", "Low-Pass Filter", "Audio / Filter and EQ",
             "Remove frequencies above the cutoff.", "audio",
             {numberParameter("frequency", "Frequency", 16000, 1000, 22000,
                              10, "Hz")},
             "sliders-horizontal"),
      effect("compressor", "Compressor", "Audio / Amplitude",
             "Control peaks and reduce dynamic range.", "audio",
             {numberParameter("threshold", "Threshold", -18, -40, -6, 1,
                              "dB"),
              numberParameter("ratio", "Ratio", 3, 1, 10, 0.1, ":1", 1),
              numberParameter("makeup", "Makeup", 2, 0, 12, 0.5, "dB", 1)},
             "volume-2"),
      effect("limiter", "Hard Limiter", "Audio / Amplitude",
             "Prevent output peaks from exceeding a ceiling.", "audio",
             {numberParameter("ceiling", "Ceiling", -1, -12, 0, 0.1, "dB",
                              1)},
             "volume-2"),
      effect("echo", "Echo", "Audio / Delay and Reverb",
             "Add a delayed, decaying copy of the signal.", "audio",
             {numberParameter("delay", "Delay", 180, 10, 1000, 1, "ms"),
              numberParameter("decay", "Decay", 0.35, 0.1, 0.9, 0.05, {},
                              2)},
             "volume-2"),
      effect("vocal_reducer", "Center Vocal Reduction",
             "Audio / Special", "Reduce centered content in a stereo mix.",
             "audio", {}, "volume-x"),
      effect("bass", "Bass", "Audio / Filter and EQ",
             "Boost or cut low frequencies.", "audio",
             {numberParameter("gain", "Gain", 3, -24, 24, 0.5, "dB", 1),
              numberParameter("frequency", "Frequency", 100, 40, 500, 1,
                              "Hz")},
             "volume-2"),
      effect("treble", "Treble", "Audio / Filter and EQ",
             "Boost or cut high frequencies.", "audio",
             {numberParameter("gain", "Gain", 3, -24, 24, 0.5, "dB", 1),
              numberParameter("frequency", "Frequency", 3000, 1000, 16000,
                              10, "Hz")},
             "volume-2"),
      effect("deesser", "De-Esser", "Audio / Noise Reduction",
             "Reduce harsh sibilance in dialogue and vocals.", "audio",
             {numberParameter("intensity", "Intensity", 45, 0, 100, 1,
                              "%"),
              numberParameter("maximum", "Maximum Reduction", 60, 0, 100,
                              1, "%"),
              numberParameter("focus", "Frequency Focus", 50, 0, 100, 1,
                              "%")},
             "volume-2"),
      effect("noise_gate", "Noise Gate", "Audio / Amplitude",
             "Attenuate audio that falls below a threshold.", "audio",
             {numberParameter("threshold", "Threshold", -36, -36, -6, 1,
                              "dB"),
              numberParameter("ratio", "Ratio", 4, 1, 20, 0.5, ":1", 1),
              numberParameter("attack", "Attack", 15, 1, 250, 1, "ms"),
              numberParameter("release", "Release", 180, 10, 1000, 1,
                              "ms")},
             "volume-2"),
      effect("loudness_normalize", "Loudness Normalize",
             "Audio / Amplitude", "Normalize output to an EBU R128 target.",
             "audio",
             {numberParameter("target", "Target Loudness", -16, -30, -5,
                              0.5, " LUFS", 1),
              numberParameter("truePeak", "True Peak", -1.5, -9, 0, 0.1,
                              " dBTP", 1)},
             "volume-2"),
      effect("chorus", "Chorus", "Audio / Modulation",
             "Add a gently modulated delayed voice.", "audio",
             {numberParameter("speed", "Speed", 0.8, 0.1, 5, 0.1, " Hz",
                              1),
              numberParameter("depth", "Depth", 2, 0.1, 10, 0.1, " ms",
                              1)},
             "volume-2"),
      effect("flanger", "Flanger", "Audio / Modulation",
             "Apply a sweeping short-delay modulation effect.", "audio",
             {numberParameter("speed", "Speed", 0.5, 0.1, 10, 0.1, " Hz",
                              1),
              numberParameter("depth", "Depth", 2, 0, 10, 0.1, " ms", 1),
              numberParameter("feedback", "Feedback", 0, -90, 90, 1, "%"),
              numberParameter("mix", "Mix", 70, 0, 100, 1, "%")},
             "volume-2"),
      effect("stereo_widener", "Stereo Widener", "Audio / Stereo Imagery",
             "Increase the perceived width of stereo audio.", "audio",
             {numberParameter("delay", "Delay", 20, 1, 100, 1, " ms"),
              numberParameter("feedback", "Feedback", 30, 0, 90, 1, "%"),
              numberParameter("crossfeed", "Crossfeed", 30, 0, 80, 1, "%"),
              numberParameter("dryMix", "Dry Mix", 80, 0, 100, 1, "%")},
             "volume-2"),
      effect("parametric_eq", "Parametric EQ", "Audio / Filter and EQ",
             "Boost or cut a single band with an adjustable Q.", "audio",
             {numberParameter("frequency", "Frequency", 1000, 20, 20000, 10,
                              "Hz"),
              numberParameter("q", "Q", 1, 0.1, 10, 0.1, {}, 1),
              numberParameter("gain", "Gain", 0, -24, 24, 0.5, "dB", 1)},
             "sliders-horizontal"),
      effect("sub_boost", "Sub Boost", "Audio / Filter and EQ",
             "Reinforce the lowest octave without muddying the mix.", "audio",
             {numberParameter("amount", "Amount", 60, 0, 100, 1, "%"),
              numberParameter("cutoff", "Cutoff", 100, 50, 900, 5, "Hz"),
              numberParameter("boost", "Max Boost", 2, 1, 12, 0.1, {}, 1)},
             "volume-2"),
      effect("virtual_bass", "Virtual Bass", "Audio / Filter and EQ",
             "Imply bass with harmonics so small speakers keep the weight.",
             "audio",
             {numberParameter("cutoff", "Cutoff", 250, 100, 500, 5, "Hz"),
              numberParameter("strength", "Strength", 2, 0.5, 3, 0.1, {}, 1)},
             "volume-2"),
      effect("dynamic_normalize", "Dynamic Normalize", "Audio / Amplitude",
             "Even out level over time instead of hitting a fixed target.",
             "audio",
             {numberParameter("frameLength", "Frame Length", 500, 10, 8000, 10,
                              "ms"),
              numberParameter("filterSize", "Smoothing", 31, 3, 301, 2),
              numberParameter("peak", "Peak", 95, 10, 100, 1, "%"),
              numberParameter("maxGain", "Max Gain", 10, 1, 100, 0.5, "x", 1)},
             "volume-2"),
      effect("speech_leveler", "Speech Leveler", "Audio / Amplitude",
             "Lift quiet dialogue and hold loud dialogue back.", "audio",
             {numberParameter("peak", "Peak", 95, 10, 100, 1, "%"),
              numberParameter("expansion", "Max Lift", 2, 1, 50, 0.5, "x", 1),
              numberParameter("compression", "Max Hold", 2, 1, 50, 0.5, "x",
                              1),
              numberParameter("threshold", "Gate", 0, 0, 100, 1, "%")},
             "volume-2"),
      effect("soft_clip", "Soft Clip", "Audio / Amplitude",
             "Round peaks over instead of squaring them off.", "audio",
             {numberParameter("threshold", "Threshold", 90, 1, 100, 1, "%"),
              numberParameter("output", "Output", 100, 10, 400, 5, "%"),
              numberParameter("amount", "Curve", 1, 0.05, 3, 0.05, {}, 2)},
             "volume-2"),
      effect("audio_contrast", "Audio Contrast", "Audio / Amplitude",
             "Sharpen transients by expanding around the midpoint.", "audio",
             {numberParameter("contrast", "Contrast", 33, 0, 100, 1, "%")},
             "volume-2"),
      effect("declick", "Declicker", "Audio / Noise Reduction",
             "Repair clicks and crackle from vinyl or bad edits.", "audio",
             {numberParameter("window", "Window", 55, 10, 100, 1, "ms"),
              numberParameter("threshold", "Threshold", 2, 1, 100, 0.5, {}, 1),
              numberParameter("burst", "Burst Fusion", 2, 0, 10, 0.5, {}, 1)},
             "volume-2"),
      effect("declip", "Declipper", "Audio / Noise Reduction",
             "Rebuild waveform peaks that were recorded into clipping.",
             "audio",
             {numberParameter("window", "Window", 55, 10, 100, 1, "ms"),
              numberParameter("threshold", "Threshold", 10, 1, 100, 0.5, {},
                              1),
              numberParameter("order", "Detail", 8, 0, 25, 1)},
             "volume-2"),
      effect("tremolo", "Tremolo", "Audio / Modulation",
             "Modulate volume with a steady oscillator.", "audio",
             {numberParameter("rate", "Rate", 5, 0.1, 20, 0.1, " Hz", 1),
              numberParameter("depth", "Depth", 50, 0, 100, 1, "%")},
             "volume-2"),
      effect("vibrato", "Vibrato", "Audio / Modulation",
             "Modulate pitch with a steady oscillator.", "audio",
             {numberParameter("rate", "Rate", 5, 0.1, 20, 0.1, " Hz", 1),
              numberParameter("depth", "Depth", 50, 0, 100, 1, "%")},
             "volume-2"),
      effect("phaser", "Phaser", "Audio / Modulation",
             "Sweep a notch through the spectrum for a whooshing sheen.",
             "audio",
             {numberParameter("delay", "Delay", 3, 0.1, 5, 0.1, " ms", 1),
              numberParameter("decay", "Decay", 40, 0, 99, 1, "%"),
              numberParameter("speed", "Speed", 0.5, 0.1, 2, 0.05, " Hz", 2)},
             "volume-2"),
      effect("auto_pan", "Auto Pan", "Audio / Modulation",
             "Sweep the signal between left and right.", "audio",
             {numberParameter("rate", "Rate", 2, 0.05, 20, 0.05, " Hz", 2),
              numberParameter("amount", "Amount", 100, 0, 100, 1, "%"),
              numberParameter("width", "Pulse Width", 100, 0, 200, 1, "%")},
             "volume-2"),
      effect("extra_stereo", "Extra Stereo", "Audio / Stereo Imagery",
             "Scale the difference between the two channels.", "audio",
             {numberParameter("difference", "Difference", 250, -100, 500, 5,
                              "%")},
             "volume-2"),
      effect("haas_stereo", "Haas Stereo", "Audio / Stereo Imagery",
             "Widen the image with very short per-side delays.", "audio",
             {numberParameter("sideGain", "Side Gain", 100, 10, 400, 5, "%"),
              numberParameter("leftDelay", "Left Delay", 2.05, 0, 40, 0.05,
                              " ms", 2),
              numberParameter("rightDelay", "Right Delay", 2.12, 0, 40, 0.05,
                              " ms", 2)},
             "volume-2"),
      effect("headphone_widen", "Headphone Widen", "Audio / Stereo Imagery",
             "Spatialize a stereo mix so headphones sound less pinned.",
             "audio", {}, "volume-2"),
      effect("pitch_shift", "Pitch Shift", "Audio / Special",
             "Move pitch in semitones and keep the original length.", "audio",
             {numberParameter("semitones", "Semitones", 0, -12, 12, 0.5, {},
                              1)},
             "volume-2"),
      effect("bit_crusher", "Bit Crusher", "Audio / Special",
             "Quantize to fewer bits and samples for a lo-fi grind.", "audio",
             {numberParameter("bits", "Bit Depth", 8, 1, 16, 0.5, {}, 1),
              numberParameter("sampleReduction", "Sample Reduction", 1, 1, 64,
                              1),
              numberParameter("mix", "Mix", 50, 0, 100, 1, "%")},
             "volume-2"),
      effect("exciter", "Harmonic Exciter", "Audio / Special",
             "Add synthesized high harmonics for air and presence.", "audio",
             {numberParameter("amount", "Amount", 1, 0, 20, 0.1, {}, 1),
              numberParameter("drive", "Harmonics", 8.5, 0.1, 10, 0.1, {}, 1),
              numberParameter("blend", "Blend", 0, -10, 10, 0.5, {}, 1),
              numberParameter("frequency", "Frequency", 7500, 2000, 12000, 100,
                              "Hz")},
             "volume-2"),
      effect("clarity", "Clarity", "Audio / Special",
             "Expand transients so the track cuts through a busy mix.",
             "audio",
             {numberParameter("intensity", "Intensity", 2, -10, 10, 0.5, {}, 1),
              boolParameter("clip", "Prevent Clipping", true)},
             "volume-2"),
      effect("reverb", "Room Reverb", "Audio / Delay and Reverb",
             "Place the signal in a room using four decaying reflections.",
             "audio",
             {numberParameter("roomSize", "Room Size", 45, 5, 100, 1, "%"),
              numberParameter("damping", "Damping", 50, 10, 90, 1, "%"),
              numberParameter("mix", "Mix", 35, 0, 100, 1, "%")},
             "volume-2")};
  }();
  return cached;
}

QVariantMap EffectRegistry::definition(const QString &effectId) {
  for (const auto &value : definitions()) {
    const QVariantMap item = value.toMap();
    if (item.value("id").toString() == effectId)
      return item;
  }
  return {};
}

bool EffectRegistry::supportsClip(const QVariantMap &definition,
                                  const QString &clipKind, bool hasAudio) {
  const QString mediaType = definition.value("mediaType").toString();
  if (mediaType == QStringLiteral("audio"))
    return hasAudio && clipKind != QStringLiteral("subtitle");
  return clipKind == QStringLiteral("video") ||
         clipKind == QStringLiteral("image");
}
